### ISSUE TITLE
Small bug in 1.3-ans

### ISSUE THREAD

**Issue by tomeru** [maxwshen/iap-appbml#3]
Line 20 of model_1-3.stan probably needs to be changed to:

`mu <- features * weights;`

Rather than:

`mu = features * weights;`

Currently running `python model_1-3.py` throws the following error:

======
ERROR at line 20

 18:    transformed parameters {
 19:      vector[N] mu;
 20:      mu = features * weights;
          ^
 21:    }

PARSER EXPECTED: <....
======

**Comment by cboix** [comment]
The <- operator is deprecated in stan:
> Warning (non-fatal): assignment operator <- deprecated in the Stan language; use = instead.

This error may be coming from an older version of Stan.
