### ISSUE TITLE
mu_a and mu_b not correctly drawn in model_1-4.stan?

### ISSUE THREAD

**Issue by tomeru** [maxwshen/iap-appbml#4]
The tutorial (iap-appbml-1-4.pdf) states that mu_a and mu_b as defined in model_1-4.stan have identifiability issues:

> The first thing to notice is that n eff and Rhat are very poor for mu a and mu b, suggesting incomplete convergence. 

 However, running the current code results in no such issues. Lines 17-18 currently already seem to be using a weak prior which gets around these issues:

`mu_a ~ normal(0, 100);`
`mu_b ~ normal(0, 100);`

Should this instead be something like...?

`mu_a ~ uniform(-5000, 5000);`
`mu_b ~ uniform(-5000, 5000);`

**Comment by maxwshen** [comment]
Ah, we accidentally left in the answer in the 1.4 folder. Corrected.

**Comment by cboix** [comment]
Note: Even then we may want to revisit this, because this model with unspecified priors doesn't consistently suffer from identifiability issues. 

Maybe update this later to directly compare the two models?
